package mydb;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import mydb.WifiRecord;

import mydb.WifiRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig wifiRecordDaoConfig;

    private final WifiRecordDao wifiRecordDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        wifiRecordDaoConfig = daoConfigMap.get(WifiRecordDao.class).clone();
        wifiRecordDaoConfig.initIdentityScope(type);

        wifiRecordDao = new WifiRecordDao(wifiRecordDaoConfig, this);

        registerDao(WifiRecord.class, wifiRecordDao);
    }
    
    public void clear() {
        wifiRecordDaoConfig.getIdentityScope().clear();
    }

    public WifiRecordDao getWifiRecordDao() {
        return wifiRecordDao;
    }

}
