package mydb;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "WIFI_RECORD".
 */
public class WifiRecord {

    private long id;
    /** Not-null value. */
    private String SSID;
    /** Not-null value. */
    private String BSSID;
    private int level;
    private int RSSI;
    private int pic_x;
    private int pic_y;
    private int floor;

    // KEEP FIELDS - put your custom fields here
    public static int _ID = 0;
    // KEEP FIELDS END

    public WifiRecord() {
    }

    public WifiRecord(long id) {
        this.id = id;
    }

    public WifiRecord(long id, String SSID, String BSSID, int level, int RSSI, int pic_x, int pic_y, int floor) {
        this.id = id;
        this.SSID = SSID;
        this.BSSID = BSSID;
        this.level = level;
        this.RSSI = RSSI;
        this.pic_x = pic_x;
        this.pic_y = pic_y;
        this.floor = floor;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getSSID() {
        return SSID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSSID(String SSID) {
        this.SSID = SSID;
    }

    /** Not-null value. */
    public String getBSSID() {
        return BSSID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBSSID(String BSSID) {
        this.BSSID = BSSID;
    }

    public int getLevel() {
        return level;
    }

    public void setLevel(int level) {
        this.level = level;
    }

    public int getRSSI() {
        return RSSI;
    }

    public void setRSSI(int RSSI) {
        this.RSSI = RSSI;
    }

    public int getPic_x() {
        return pic_x;
    }

    public void setPic_x(int pic_x) {
        this.pic_x = pic_x;
    }

    public int getPic_y() {
        return pic_y;
    }

    public void setPic_y(int pic_y) {
        this.pic_y = pic_y;
    }

    public int getFloor() {
        return floor;
    }

    public void setFloor(int floor) {
        this.floor = floor;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
